/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackerIndexRouteImport } from './routes/tracker/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as QuranIndexRouteImport } from './routes/quran/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as TrackerKhatamRouteImport } from './routes/tracker/khatam'
import { Route as QuranSurahNumberRouteImport } from './routes/quran/$surahNumber'
import { Route as JournalNewRouteImport } from './routes/journal/new'
import { Route as JournalEntryIdRouteImport } from './routes/journal/$entryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerIndexRoute = TrackerIndexRouteImport.update({
  id: '/tracker/',
  path: '/tracker/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerKhatamRoute = TrackerKhatamRouteImport.update({
  id: '/tracker/khatam',
  path: '/tracker/khatam',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSurahNumberRoute = QuranSurahNumberRouteImport.update({
  id: '/quran/$surahNumber',
  path: '/quran/$surahNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntryIdRoute = JournalEntryIdRouteImport.update({
  id: '/journal/$entryId',
  path: '/journal/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/journal/new': typeof JournalNewRoute
  '/quran/$surahNumber': typeof QuranSurahNumberRoute
  '/tracker/khatam': typeof TrackerKhatamRoute
  '/journal/': typeof JournalIndexRoute
  '/quran/': typeof QuranIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/tracker/': typeof TrackerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/journal/new': typeof JournalNewRoute
  '/quran/$surahNumber': typeof QuranSurahNumberRoute
  '/tracker/khatam': typeof TrackerKhatamRoute
  '/journal': typeof JournalIndexRoute
  '/quran': typeof QuranIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/tracker': typeof TrackerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/journal/new': typeof JournalNewRoute
  '/quran/$surahNumber': typeof QuranSurahNumberRoute
  '/tracker/khatam': typeof TrackerKhatamRoute
  '/journal/': typeof JournalIndexRoute
  '/quran/': typeof QuranIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/tracker/': typeof TrackerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journal/$entryId'
    | '/journal/new'
    | '/quran/$surahNumber'
    | '/tracker/khatam'
    | '/journal/'
    | '/quran/'
    | '/settings/'
    | '/stats/'
    | '/tracker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journal/$entryId'
    | '/journal/new'
    | '/quran/$surahNumber'
    | '/tracker/khatam'
    | '/journal'
    | '/quran'
    | '/settings'
    | '/stats'
    | '/tracker'
  id:
    | '__root__'
    | '/'
    | '/journal/$entryId'
    | '/journal/new'
    | '/quran/$surahNumber'
    | '/tracker/khatam'
    | '/journal/'
    | '/quran/'
    | '/settings/'
    | '/stats/'
    | '/tracker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JournalEntryIdRoute: typeof JournalEntryIdRoute
  JournalNewRoute: typeof JournalNewRoute
  QuranSurahNumberRoute: typeof QuranSurahNumberRoute
  TrackerKhatamRoute: typeof TrackerKhatamRoute
  JournalIndexRoute: typeof JournalIndexRoute
  QuranIndexRoute: typeof QuranIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  TrackerIndexRoute: typeof TrackerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/': {
      id: '/tracker/'
      path: '/tracker'
      fullPath: '/tracker/'
      preLoaderRoute: typeof TrackerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/khatam': {
      id: '/tracker/khatam'
      path: '/tracker/khatam'
      fullPath: '/tracker/khatam'
      preLoaderRoute: typeof TrackerKhatamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$surahNumber': {
      id: '/quran/$surahNumber'
      path: '/quran/$surahNumber'
      fullPath: '/quran/$surahNumber'
      preLoaderRoute: typeof QuranSurahNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/new': {
      id: '/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$entryId': {
      id: '/journal/$entryId'
      path: '/journal/$entryId'
      fullPath: '/journal/$entryId'
      preLoaderRoute: typeof JournalEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JournalEntryIdRoute: JournalEntryIdRoute,
  JournalNewRoute: JournalNewRoute,
  QuranSurahNumberRoute: QuranSurahNumberRoute,
  TrackerKhatamRoute: TrackerKhatamRoute,
  JournalIndexRoute: JournalIndexRoute,
  QuranIndexRoute: QuranIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  TrackerIndexRoute: TrackerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
